<a href="https://colab.research.google.com/github/ochilovu2010/IOAI/blob/main/NitroAI/AgencyKazakhistanAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
#https://judge.nitro-ai.org/competitions/cpfed/ai-olymp-2026-second-round/1/view
import argparse
import os
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import adjusted_rand_score

In [67]:
train = pd.read_csv("/content/train_data.csv")
test = pd.read_csv("/content/test_data.csv")
sample = pd.read_csv("/content/sample_output.csv")

In [68]:
train

,submission_id,author_id,f_naming_camel_ratio,f_naming_snake_ratio,f_naming_single_char_ratio,f_naming_avg_length,f_indent_tab_ratio,f_indent_2space_ratio,f_indent_4space_ratio,f_indent_mixed_ratio,...,f_struct_avg_func_length,f_struct_avg_block_depth,f_struct_import_count,f_struct_class_ratio,f_literal_magic_num_ratio,f_literal_string_ratio,f_literal_fstring_ratio,f_ctrl_for_vs_while,f_ctrl_if_else_ratio,f_ctrl_ternary_ratio
0,0,0,0.707742,0.705716,0.500000,15.000000,0.312399,0.985148,0.817974,0.174559,...,35.897720,1.727204,1.000000,0.971588,0.183834,0.133189,0.024288,0.608982,0.225093,0.003462
1,1,0,1.000000,0.351013,0.422092,15.000000,0.041397,1.000000,0.936290,0.295282,...,36.098610,4.000000,3.766803,0.839646,0.200000,0.120671,0.344385,0.761390,0.266311,0.007150
2,2,0,1.000000,0.806836,0.289056,10.222247,0.342164,0.940515,0.627432,0.300000,...,8.445196,2.451851,1.000000,1.000000,0.080916,0.118047,0.319475,0.960111,0.200000,0.023516
3,3,0,0.505945,0.115539,0.413924,15.000000,0.256685,0.781819,0.952204,0.053406,...,34.944036,2.822214,7.430129,1.000000,0.118855,0.150000,0.000000,0.686564,0.200000,0.074722
4,4,0,0.637548,0.303150,0.379063,11.679317,0.005170,0.939610,0.000000,0.240466,...,28.825091,4.000000,3.880769,1.000000,0.143277,0.125917,0.126680,0.822993,0.267053,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,1113,199,1.000000,0.334492,0.251800,7.085894,0.000000,0.759147,0.456377,0.176574,...,40.000000,3.917894,14.840458,0.046883,0.161895,0.112122,0.156169,0.837836,0.660690,0.000000
1114,1114,199,0.518931,0.463849,0.330968,9.745495,0.163092,0.710650,0.898319,0.182799,...,37.643128,4.000000,1.000000,0.129797,0.140996,0.084463,0.120331,1.000000,0.658483,0.021436
1115,1115,199,0.663205,0.259468,0.000000,9.105113,0.000000,0.813188,0.667028,0.295657,...,40.000000,2.755057,7.014342,0.000000,0.200000,0.045298,0.500000,0.935225,0.232416,0.076255
1116,1116,199,0.898155,0.119918,0.350459,7.841991,0.149908,1.000000,0.617422,0.270001,...,22.247560,2.822088,5.803896,0.078060,0.088827,0.062172,0.098056,0.988692,0.581024,0.056248
1117,1117,199,0.396121,0.098092,0.500000,7.765979,0.000000,0.440252,0.849181,0.300000,...,27.929693,2.698767,12.287678,0.000000,0.136807,0.125342,0.112154,0.988592,0.286890,0.044834

In [97]:
test

,subtaskID,datapointID,f_naming_camel_ratio,f_naming_snake_ratio,f_naming_single_char_ratio,f_naming_avg_length,f_indent_tab_ratio,f_indent_2space_ratio,f_indent_4space_ratio,f_indent_mixed_ratio,...,f_struct_avg_func_length,f_struct_avg_block_depth,f_struct_import_count,f_struct_class_ratio,f_literal_magic_num_ratio,f_literal_string_ratio,f_literal_fstring_ratio,f_ctrl_for_vs_while,f_ctrl_if_else_ratio,f_ctrl_ternary_ratio
0,1,1324636578,0.478350,0.440615,0.233303,10.294964,0.829591,0.277773,0.578284,0.118437,...,29.483793,3.523624,18.313917,0.317231,0.102571,0.150000,0.041096,0.848397,0.484024,0.100000
1,1,227854337,0.844751,0.149255,0.462381,14.685766,0.049621,1.000000,0.000000,0.000000,...,40.000000,3.053644,1.000000,0.000000,0.134809,0.018074,0.497529,1.000000,0.602129,0.066492
2,1,869491723,0.270948,0.217354,0.072720,15.000000,0.635907,0.218743,0.350560,0.300000,...,24.930503,2.004381,6.754038,0.000000,0.130266,0.062495,0.000000,0.500000,0.547036,0.028547
3,1,996965456,1.000000,0.711182,0.351083,4.165197,0.702610,0.000000,1.000000,0.108054,...,18.593010,3.251310,3.894229,1.000000,0.200000,0.072005,0.437584,0.635751,0.622681,0.000047
4,1,217696908,1.000000,0.262388,0.346098,5.263867,0.751065,0.694040,0.425693,0.248341,...,28.137468,4.000000,11.658879,0.136517,0.079557,0.083563,0.154792,0.889355,0.766337,0.061420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1,1065592597,0.565673,0.689874,0.320367,5.321018,0.088646,1.000000,0.608986,0.255709,...,14.755683,4.000000,8.502583,0.130687,0.200000,0.123261,0.107563,0.734553,0.282447,0.038827
541,1,919288516,1.000000,0.767540,0.500000,8.289921,0.669712,0.000000,0.184087,0.233794,...,25.190499,2.121488,8.345237,0.912665,0.107696,0.047428,0.231663,0.771702,0.693175,0.100000
542,1,505016506,0.269697,0.818848,0.395132,3.569315,0.266016,1.000000,0.092652,0.119793,...,26.829021,1.000000,11.045001,1.000000,0.109388,0.037147,0.500000,0.500000,0.431098,0.073608
543,1,687013593,0.961359,1.000000,0.194665,15.000000,0.160732,0.234769,0.236289,0.000000,...,29.801188,1.960751,17.368355,0.658995,0.101546,0.150000,0.332075,0.806754,0.473165,0.000000
544,1,1097631802,0.000960,0.272130,0.389274,11.127747,0.178870,0.905902,0.230371,0.032589,...,23.561320,4.000000,17.797316,0.708723,0.011183,0.000000,0.000000,0.722520,0.200000,0.010710

In [81]:
scaler = StandardScaler()
tresholds = [0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4]
scores = []
for x in tresholds:

  model = AgglomerativeClustering(
      n_clusters = None,
      distance_threshold =x,
      metric = 'cosine',
      linkage = 'average'
  )
  X = scaler.fit_transform(train.drop(columns=['submission_id', 'author_id']))

  labels = model.fit_predict(X)
  score = adjusted_rand_score(labels, train['author_id'])
  scores.append(score)

In [85]:
print(np.argmax(np.array(scores)))

3

In [95]:
threshold = 3

In [96]:
model = AgglomerativeClustering(
    n_clusters = None,
    distance_threshold =0.6,
    metric = 'cosine',
    linkage = 'average'
)

In [99]:
scaled_features = scaler.fit_transform(test.drop(columns = ['subtaskID', 'datapointID']))
predictions = model.fit_predict(scaled_features)

In [102]:
submission = pd.DataFrame({
    'subtaskID': test['subtaskID'],
    'datapointID': test['datapointID'],
    'answer':predictions
})

In [103]:
submission.to_csv('mysubmission.csv', index = False)