<a href="https://colab.research.google.com/github/ochilovu2010/IOAI/blob/main/NitroAI/Cybersecurity_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [71]:
train = pd.read_csv("/content/train_data.csv")
test = pd.read_csv("/content/test_data.csv")
sample = pd.read_csv("/content/sample_output.csv")

In [72]:
train

,ID,Timestamp,Suspicious_Port_Activity,Traffic_Volume_Variation,Packet_Length_Anomaly,Malware_Score,Threat_Level_Index,User_Behavior_Score,Geo_Dispersion,Payload_Entropy,Login_Attempts,Device_Response_Time,Session_Duration,Packet_Retry_Rate,Anomaly_Tendency,Attack Type
0,38478,2023-02-10 00:35:00,51.454294,53.193234,50.854265,0.343061,-2.829257,-1.150952,96.510346,51.638318,1.427135e+07,8.254265e+05,40.059209,21.344372,-27.224217,1
1,28447,2023-01-06 10:49:00,66.049091,60.865730,63.611018,5.242388,-5.684331,-0.996886,4.203410,9.657115,1.300129e+03,0.000000e+00,-5.968370,30.608016,-13.656677,0
2,30883,2023-01-08 21:35:00,29.509985,29.381920,26.477660,13.095004,3.713273,-1.542933,56.986902,42.720874,6.537937e+02,0.000000e+00,17.269407,11.348135,-6.043118,0
3,10247,2023-01-04 19:13:00,47.698458,47.038595,47.511664,-11.713488,-5.855172,-0.114920,62.225258,56.349504,3.815307e+03,0.000000e+00,15.670151,20.733735,-7.827522,0
4,14198,2023-01-24 20:57:00,52.066922,51.621483,50.422555,18.491120,10.658195,1.540859,25.647005,13.831798,-2.512838e+07,4.236788e+06,12.687819,24.197432,16.831704,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13351,10586,2023-02-22 11:08:00,61.313450,62.285584,66.081125,-16.172590,-2.326001,1.216705,91.445967,-4.929572,2.169712e+03,0.000000e+00,29.964378,24.115536,-42.548858,0
13352,17907,2023-01-25 08:28:00,47.450431,47.719287,48.410581,-16.407919,-3.932880,1.513555,31.274805,-51.563591,2.089759e+03,0.000000e+00,12.823899,22.830285,-29.836513,0
13353,21615,2023-01-21 07:34:00,50.577761,48.207897,50.869976,19.963207,12.458160,-0.074276,76.307840,-27.251740,1.193038e+05,6.328211e+06,11.935022,17.355606,10.697266,2
13354,5752,2023-02-17 04:59:00,61.982918,63.628530,67.656022,1.513651,9.905296,NaN,73.776103,52.092306,5.120911e+03,0.000000e+00,19.937009,25.267148,8.419759,0
13355,1762,2023-01-08 08:48:00,49.415216,48.452817,49.998711,32.610874,10.911052,0.834872,99.074664,-21.141853,1.122525e+08,1.522367e+07,35.083660,16.733160,5.911933,2

In [73]:
test

,ID,Timestamp,Suspicious_Port_Activity,Traffic_Volume_Variation,Packet_Length_Anomaly,Malware_Score,Threat_Level_Index,User_Behavior_Score,Geo_Dispersion,Payload_Entropy,Login_Attempts,Device_Response_Time,Session_Duration,Packet_Retry_Rate,Anomaly_Tendency
0,12633,2023-01-06 18:42:00,52.676002,51.036281,51.584358,24.918044,2.453998,-1.912664,17.110169,-20.721761,6.863287e+06,9.988945e+06,12.638554,19.571961,30.163868
1,24448,2023-02-09 17:38:00,34.521340,33.285478,36.457937,21.243958,10.715173,-0.832558,79.533482,-9.685447,-6.805482e+07,2.631087e+07,24.512180,13.107590,10.169910
2,14208,2023-02-18 09:06:00,60.802694,60.730913,58.413126,15.055070,-0.759497,0.289197,3.176137,42.232753,1.879409e+07,3.070784e+06,-13.531991,27.092224,7.439020
3,39654,2023-01-23 04:31:00,50.054000,49.323942,51.133184,24.206964,7.180573,0.934965,94.608307,-34.012325,-1.999618e+07,6.131093e+06,7.141197,22.616820,12.690832
4,337,2023-02-12 00:28:00,44.431133,44.047129,46.160836,21.007636,15.675149,1.508040,68.590797,-8.049880,-5.071975e+06,9.095271e+06,11.119575,22.508857,7.490883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,38228,2023-02-01 20:37:00,40.365558,42.888239,40.445284,0.528988,1.527553,-0.233116,61.759516,-32.960899,1.367746e+03,0.000000e+00,11.954073,16.766390,19.192912
7496,8568,2023-02-11 02:34:00,47.661617,49.092103,50.274326,27.947167,14.990121,-1.530983,53.826759,4.652825,-9.572391e+06,5.951209e+05,11.356634,25.900720,25.283231
7497,1435,2023-01-14 11:53:00,51.668364,51.489521,51.122505,12.537508,-1.726501,1.295477,53.903648,-40.583001,-7.455911e+07,7.288900e+06,36.600587,25.582709,14.559145
7498,9879,2023-02-04 01:26:00,54.172660,54.611388,54.121199,2.289232,2.387826,-0.597842,83.307020,36.492115,6.863681e+02,0.000000e+00,30.544559,26.478434,23.469777
7499,17025,2023-01-23 23:44:00,54.953850,54.779608,54.403308,25.395724,10.191529,NaN,11.802503,42.905126,-2.153372e+07,8.336968e+06,-8.320041,26.672622,-8.907672

In [74]:
sample

       subtaskID  datapointID answer
0              1        12633  value
1              1        24448  value
2              1        14208  value
3              1        39654  value
4              1          337  value
...          ...          ...    ...
14995          2        38228      0
14996          2         8568      0
14997          2         1435      0
14998          2         9879      0
14999          2        17025      0

[15000 rows x 3 columns]

In [75]:
test['Timestamp'] = pd.to_datetime(test['Timestamp'])

In [76]:
test['Timestamp']

0      2023-01-06 18:42:00
1      2023-02-09 17:38:00
2      2023-02-18 09:06:00
3      2023-01-23 04:31:00
4      2023-02-12 00:28:00
               ...
7495   2023-02-01 20:37:00
7496   2023-02-11 02:34:00
7497   2023-01-14 11:53:00
7498   2023-02-04 01:26:00
7499   2023-01-23 23:44:00
Name: Timestamp, Length: 7500, dtype: datetime64[ns]

In [77]:
test['hour'] = test['Timestamp'].dt.hour>=12

In [78]:
test['hour']

0        True
1        True
2       False
3       False
4       False
        ...
7495     True
7496    False
7497    False
7498    False
7499     True
Name: hour, Length: 7500, dtype: bool

In [79]:
test['subtask1'] = test['hour'].map({True:'PM', False: 'AM'})

In [80]:
submission1 = pd.DataFrame({
    'subtaskID':1,
    'datapointID': test['ID'],
    'answer':test['subtask1']
})

In [81]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.13/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)

In [82]:
from catboost import CatBoostClassifier
train['Timestamp'] = pd.to_datetime(train['Timestamp'])
model = CatBoostClassifier()
model.fit(train.drop(columns = ['Attack Type', 'ID']), train['Attack Type'])

Learning rate set to 0.090309
0:	learn: 0.9699105	total: 18.8ms	remaining: 18.7s
1:	learn: 0.8701754	total: 33.8ms	remaining: 16.9s
2:	learn: 0.7889722	total: 47.9ms	remaining: 15.9s
3:	learn: 0.7210879	total: 62.8ms	remaining: 15.6s
4:	learn: 0.6651543	total: 80.3ms	remaining: 16s
5:	learn: 0.6152754	total: 95.1ms	remaining: 15.7s
6:	learn: 0.5725110	total: 110ms	remaining: 15.6s
7:	learn: 0.5346247	total: 125ms	remaining: 15.5s
8:	learn: 0.5023400	total: 140ms	remaining: 15.4s
9:	learn: 0.4733907	total: 155ms	remaining: 15.4s
10:	learn: 0.4481256	total: 170ms	remaining: 15.3s
11:	learn: 0.4249766	total: 185ms	remaining: 15.3s
12:	learn: 0.4049630	total: 202ms	remaining: 15.4s
13:	learn: 0.3872946	total: 217ms	remaining: 15.3s
14:	learn: 0.3712516	total: 231ms	remaining: 15.2s
15:	learn: 0.3571165	total: 246ms	remaining: 15.1s
16:	learn: 0.3440133	total: 261ms	remaining: 15.1s
17:	learn: 0.3323099	total: 281ms	remaining: 15.3s
18:	learn: 0.3215954	total: 297ms	remaining: 15.3s
19:	learn: 0.3116252	total: 312ms	remaining: 15.3s
20:	learn: 0.3025406	total: 327ms	remaining: 15.3s
21:	learn: 0.2944129	total: 342ms	remaining: 15.2s
22:	learn: 0.2873422	total: 358ms	remaining: 15.2s
23:	learn: 0.2807777	total: 375ms	remaining: 15.3s
24:	learn: 0.2747991	total: 395ms	remaining: 15.4s
25:	learn: 0.2698260	total: 418ms	remaining: 15.7s
26:	learn: 0.2645548	total: 434ms	remaining: 15.6s
27:	learn: 0.2596942	total: 449ms	remaining: 15.6s
28:	learn: 0.2556351	total: 464ms	remaining: 15.5s
29:	learn: 0.2515100	total: 480ms	remaining: 15.5s
30:	learn: 0.2474391	total: 517ms	remaining: 16.2s
31:	learn: 0.2443263	total: 545ms	remaining: 16.5s
32:	learn: 0.2412370	total: 570ms	remaining: 16.7s
33:	learn: 0.2389438	total: 593ms	remaining: 16.9s
34:	learn: 0.2359845	total: 622ms	remaining: 17.2s
35:	learn: 0.2337977	total: 641ms	remaining: 17.2s
36:	learn: 0.2316710	total: 656ms	remaining: 17.1s
37:	learn: 0.2302509	total: 670ms	remaining: 17s
38:	learn: 0.2291083	total: 687ms	remaining: 16.9s
39:	learn: 0.2277255	total: 716ms	remaining: 17.2s
40:	learn: 0.2259528	total: 748ms	remaining: 17.5s
41:	learn: 0.2242060	total: 773ms	remaining: 17.6s
42:	learn: 0.2234197	total: 798ms	remaining: 17.8s
43:	learn: 0.2222722	total: 827ms	remaining: 18s
44:	learn: 0.2217352	total: 859ms	remaining: 18.2s
45:	learn: 0.2210301	total: 887ms	remaining: 18.4s
46:	learn: 0.2194494	total: 918ms	remaining: 18.6s
47:	learn: 0.2186434	total: 948ms	remaining: 18.8s
48:	learn: 0.2178447	total: 982ms	remaining: 19.1s
49:	learn: 0.2170119	total: 1.02s	remaining: 19.3s
50:	learn: 0.2164354	total: 1.05s	remaining: 19.6s
51:	learn: 0.2155774	total: 1.08s	remaining: 19.8s
52:	learn: 0.2148378	total: 1.12s	remaining: 20s
53:	learn: 0.2142073	total: 1.16s	remaining: 20.3s
54:	learn: 0.2136913	total: 1.19s	remaining: 20.4s
55:	learn: 0.2133205	total: 1.22s	remaining: 20.5s
56:	learn: 0.2123002	total: 1.25s	remaining: 20.6s
57:	learn: 0.2119618	total: 1.29s	remaining: 20.9s
58:	learn: 0.2117021	total: 1.34s	remaining: 21.4s
59:	learn: 0.2114913	total: 1.38s	remaining: 21.6s
60:	learn: 0.2110238	total: 1.43s	remaining: 22.1s
61:	learn: 0.2105998	total: 1.48s	remaining: 22.4s
62:	learn: 0.2101235	total: 1.52s	remaining: 22.7s
63:	learn: 0.2097835	total: 1.55s	remaining: 22.7s
64:	learn: 0.2092285	total: 1.58s	remaining: 22.7s
65:	learn: 0.2088123	total: 1.61s	remaining: 22.8s
66:	learn: 0.2084174	total: 1.64s	remaining: 22.8s
67:	learn: 0.2078797	total: 1.67s	remaining: 22.9s
68:	learn: 0.2075109	total: 1.69s	remaining: 22.9s
69:	learn: 0.2069923	total: 1.72s	remaining: 22.9s
70:	learn: 0.2066229	total: 1.75s	remaining: 23s
71:	learn: 0.2062087	total: 1.78s	remaining: 23s
72:	learn: 0.2059196	total: 1.81s	remaining: 23s
73:	learn: 0.2054711	total: 1.84s	remaining: 23s
74:	learn: 0.2051616	total: 1.87s	remaining: 23.1s
75:	learn: 0.2048529	total: 1.91s	remaining: 23.3s
76:	learn: 0.2046557	total: 1.95s	remaining: 23.3s
77:	learn: 0.2042000	total: 1.97s	remaining: 23.3s
78:	learn: 0.2038923	total: 2s	remaining: 23.3s
79:	learn: 0.2034859	total: 2.03s	remaining: 23.3s
80:	learn: 0.2031475	total: 2.06s	remaining: 23.4s
81:	learn: 0.2026413	total: 2.1s	remaining: 23.5s
82:	learn: 0.2022469	total: 2.12s	remaining: 23.5s
83:	learn: 0.2020105	total: 2.15s	remaining: 23.5s
84:	learn: 0.2017677	total: 2.18s	remaining: 23.5s
85:	learn: 0.2011851	total: 2.21s	remaining: 23.5s
86:	learn: 0.2009438	total: 2.24s	remaining: 23.5s
87:	learn: 0.2006959	total: 2.27s	remaining: 23.5s
88:	learn: 0.2003583	total: 2.29s	remaining: 23.5s
89:	learn: 0.2001952	total: 2.32s	remaining: 23.5s
90:	learn: 0.1999917	total: 2.35s	remaining: 23.5s
91:	learn: 0.1998419	total: 2.38s	remaining: 23.4s
92:	learn: 0.1995630	total: 2.4s	remaining: 23.4s
93:	learn: 0.1993334	total: 2.41s	remaining: 23.2s
94:	learn: 0.1990533	total: 2.43s	remaining: 23.1s
95:	learn: 0.1989109	total: 2.44s	remaining: 23s
96:	learn: 0.1985720	total: 2.46s	remaining: 22.9s
97:	learn: 0.1982591	total: 2.47s	remaining: 22.7s
98:	learn: 0.1978995	total: 2.48s	remaining: 22.6s
99:	learn: 0.1976715	total: 2.5s	remaining: 22.5s
100:	learn: 0.1974620	total: 2.52s	remaining: 22.4s
101:	learn: 0.1972885	total: 2.53s	remaining: 22.3s
102:	learn: 0.1969586	total: 2.55s	remaining: 22.2s
103:	learn: 0.1966176	total: 2.56s	remaining: 22.1s
104:	learn: 0.1964548	total: 2.58s	remaining: 22s
105:	learn: 0.1960326	total: 2.59s	remaining: 21.9s
106:	learn: 0.1958263	total: 2.61s	remaining: 21.8s
107:	learn: 0.1955119	total: 2.63s	remaining: 21.7s
108:	learn: 0.1952461	total: 2.64s	remaining: 21.6s
109:	learn: 0.1948801	total: 2.66s	remaining: 21.5s
110:	learn: 0.1947130	total: 2.67s	remaining: 21.4s
111:	learn: 0.1945501	total: 2.69s	remaining: 21.3s
112:	learn: 0.1943379	total: 2.7s	remaining: 21.2s
113:	learn: 0.1941693	total: 2.72s	remaining: 21.1s
114:	learn: 0.1938171	total: 2.73s	remaining: 21s
115:	learn: 0.1936238	total: 2.75s	remaining: 20.9s
116:	learn: 0.1935078	total: 2.77s	remaining: 20.9s
117:	learn: 0.1933439	total: 2.79s	remaining: 20.8s
118:	learn: 0.1931423	total: 2.81s	remaining: 20.8s
119:	learn: 0.1928981	total: 2.83s	remaining: 20.8s
120:	learn: 0.1925025	total: 2.85s	remaining: 20.7s
121:	learn: 0.1922845	total: 2.88s	remaining: 20.7s
122:	learn: 0.1921052	total: 2.9s	remaining: 20.7s
123:	learn: 0.1919022	total: 2.93s	remaining: 20.7s
124:	learn: 0.1917208	total: 2.96s	remaining: 20.7s
125:	learn: 0.1915847	total: 2.99s	remaining: 20.7s
126:	learn: 0.1912896	total: 3.01s	remaining: 20.7s
127:	learn: 0.1911078	total: 3.04s	remaining: 20.7s
128:	learn: 0.1907412	total: 3.07s	remaining: 20.8s
129:	learn: 0.1905967	total: 3.12s	remaining: 20.9s
130:	learn: 0.1904568	total: 3.19s	remaining: 21.2s
131:	learn: 0.1902994	total: 3.26s	remaining: 21.4s
132:	learn: 0.1899945	total: 3.29s	remaining: 21.5s
133:	learn: 0.1897596	total: 3.32s	remaining: 21.5s
134:	learn: 0.1894914	total: 3.35s	remaining: 21.4s
135:	learn: 0.1893657	total: 3.37s	remaining: 21.4s
136:	learn: 0.1890712	total: 3.41s	remaining: 21.5s
137:	learn: 0.1889212	total: 3.43s	remaining: 21.4s
138:	learn: 0.1886365	total: 3.47s	remaining: 21.5s
139:	learn: 0.1885334	total: 3.51s	remaining: 21.6s
140:	learn: 0.1881893	total: 3.54s	remaining: 21.6s
141:	learn: 0.1878757	total: 3.57s	remaining: 21.6s
142:	learn: 0.1876236	total: 3.6s	remaining: 21.6s
143:	learn: 0.1873931	total: 3.64s	remaining: 21.7s
144:	learn: 0.1871293	total: 3.67s	remaining: 21.6s
145:	learn: 0.1869903	total: 3.71s	remaining: 21.7s
146:	learn: 0.1867745	total: 3.75s	remaining: 21.8s
147:	learn: 0.1866745	total: 3.79s	remaining: 21.8s
148:	learn: 0.1864468	total: 3.82s	remaining: 21.8s
149:	learn: 0.1862389	total: 3.86s	remaining: 21.9s
150:	learn: 0.1861012	total: 3.89s	remaining: 21.9s
151:	learn: 0.1859266	total: 3.94s	remaining: 22s
152:	learn: 0.1857402	total: 3.99s	remaining: 22.1s
153:	learn: 0.1854685	total: 4.02s	remaining: 22.1s
154:	learn: 0.1853301	total: 4.04s	remaining: 22s
155:	learn: 0.1850023	total: 4.08s	remaining: 22.1s
156:	learn: 0.1846621	total: 4.12s	remaining: 22.1s
157:	learn: 0.1845024	total: 4.15s	remaining: 22.1s
158:	learn: 0.1842069	total: 4.24s	remaining: 22.4s
159:	learn: 0.1838882	total: 4.28s	remaining: 22.5s
160:	learn: 0.1837574	total: 4.33s	remaining: 22.5s
161:	learn: 0.1835437	total: 4.36s	remaining: 22.6s
162:	learn: 0.1830300	total: 4.39s	remaining: 22.6s
163:	learn: 0.1828824	total: 4.42s	remaining: 22.5s
164:	learn: 0.1825457	total: 4.45s	remaining: 22.5s
165:	learn: 0.1822477	total: 4.5s	remaining: 22.6s
166:	learn: 0.1820490	total: 4.54s	remaining: 22.7s
167:	learn: 0.1819121	total: 4.58s	remaining: 22.7s
168:	learn: 0.1817478	total: 4.6s	remaining: 22.6s
169:	learn: 0.1815491	total: 4.67s	remaining: 22.8s
170:	learn: 0.1813596	total: 4.7s	remaining: 22.8s
171:	learn: 0.1811653	total: 4.75s	remaining: 22.9s
172:	learn: 0.1808869	total: 4.78s	remaining: 22.8s
173:	learn: 0.1807480	total: 4.81s	remaining: 22.8s
174:	learn: 0.1806216	total: 4.85s	remaining: 22.9s
175:	learn: 0.1804826	total: 4.91s	remaining: 23s
176:	learn: 0.1803140	total: 4.95s	remaining: 23s
177:	learn: 0.1801158	total: 4.98s	remaining: 23s
178:	learn: 0.1798340	total: 5.01s	remaining: 23s
179:	learn: 0.1796955	total: 5.04s	remaining: 23s
180:	learn: 0.1795244	total: 5.07s	remaining: 23s
181:	learn: 0.1792645	total: 5.1s	remaining: 22.9s
182:	learn: 0.1791102	total: 5.14s	remaining: 22.9s
183:	learn: 0.1789099	total: 5.19s	remaining: 23s
184:	learn: 0.1787159	total: 5.25s	remaining: 23.1s
185:	learn: 0.1783916	total: 5.31s	remaining: 23.2s
186:	learn: 0.1782237	total: 5.37s	remaining: 23.3s
187:	learn: 0.1780389	total: 5.43s	remaining: 23.5s
188:	learn: 0.1778203	total: 5.49s	remaining: 23.5s
189:	learn: 0.1776520	total: 5.52s	remaining: 23.5s
190:	learn: 0.1774936	total: 5.55s	remaining: 23.5s
191:	learn: 0.1772199	total: 5.59s	remaining: 23.5s
192:	learn: 0.1770515	total: 5.63s	remaining: 23.6s
193:	learn: 0.1768518	total: 5.7s	remaining: 23.7s
194:	learn: 0.1766695	total: 5.74s	remaining: 23.7s
195:	learn: 0.1764401	total: 5.78s	remaining: 23.7s
196:	learn: 0.1761772	total: 5.81s	remaining: 23.7s
197:	learn: 0.1759205	total: 5.87s	remaining: 23.8s
198:	learn: 0.1756356	total: 5.94s	remaining: 23.9s
199:	learn: 0.1754662	total: 5.96s	remaining: 23.9s
200:	learn: 0.1753698	total: 5.99s	remaining: 23.8s
201:	learn: 0.1751883	total: 6.02s	remaining: 23.8s
202:	learn: 0.1748902	total: 6.05s	remaining: 23.8s
203:	learn: 0.1745989	total: 6.08s	remaining: 23.7s
204:	learn: 0.1742721	total: 6.11s	remaining: 23.7s
205:	learn: 0.1741328	total: 6.14s	remaining: 23.7s
206:	learn: 0.1739969	total: 6.18s	remaining: 23.7s
207:	learn: 0.1737964	total: 6.22s	remaining: 23.7s
208:	learn: 0.1736579	total: 6.25s	remaining: 23.7s
209:	learn: 0.1733817	total: 6.29s	remaining: 23.7s
210:	learn: 0.1731727	total: 6.35s	remaining: 23.7s
211:	learn: 0.1730573	total: 6.42s	remaining: 23.9s
212:	learn: 0.1728372	total: 6.48s	remaining: 24s
213:	learn: 0.1725116	total: 6.58s	remaining: 24.2s
214:	learn: 0.1724452	total: 6.63s	remaining: 24.2s
215:	learn: 0.1723063	total: 6.67s	remaining: 24.2s
216:	learn: 0.1722076	total: 6.7s	remaining: 24.2s
217:	learn: 0.1720185	total: 6.75s	remaining: 24.2s
218:	learn: 0.1718948	total: 6.77s	remaining: 24.2s
219:	learn: 0.1717538	total: 6.8s	remaining: 24.1s
220:	learn: 0.1716557	total: 6.86s	remaining: 24.2s
221:	learn: 0.1715135	total: 6.88s	remaining: 24.1s
222:	learn: 0.1713058	total: 6.91s	remaining: 24.1s
223:	learn: 0.1711734	total: 6.94s	remaining: 24s
224:	learn: 0.1710404	total: 6.98s	remaining: 24.1s
225:	learn: 0.1708336	total: 7.01s	remaining: 24s
226:	learn: 0.1706427	total: 7.05s	remaining: 24s
227:	learn: 0.1704921	total: 7.1s	remaining: 24.1s
228:	learn: 0.1703717	total: 7.15s	remaining: 24.1s
229:	learn: 0.1702463	total: 7.18s	remaining: 24s
230:	learn: 0.1701334	total: 7.21s	remaining: 24s
231:	learn: 0.1699714	total: 7.24s	remaining: 24s
232:	learn: 0.1697201	total: 7.27s	remaining: 23.9s
233:	learn: 0.1695559	total: 7.3s	remaining: 23.9s
234:	learn: 0.1693723	total: 7.38s	remaining: 24s
235:	learn: 0.1690458	total: 7.51s	remaining: 24.3s
236:	learn: 0.1688916	total: 7.67s	remaining: 24.7s
237:	learn: 0.1686336	total: 7.72s	remaining: 24.7s
238:	learn: 0.1685942	total: 7.77s	remaining: 24.7s
239:	learn: 0.1683916	total: 7.83s	remaining: 24.8s
240:	learn: 0.1682236	total: 7.89s	remaining: 24.8s
241:	learn: 0.1680497	total: 7.94s	remaining: 24.9s
242:	learn: 0.1679305	total: 7.97s	remaining: 24.8s
243:	learn: 0.1678099	total: 8.01s	remaining: 24.8s
244:	learn: 0.1676012	total: 8.06s	remaining: 24.8s
245:	learn: 0.1673550	total: 8.12s	remaining: 24.9s
246:	learn: 0.1670989	total: 8.18s	remaining: 24.9s
247:	learn: 0.1670094	total: 8.24s	remaining: 25s
248:	learn: 0.1669324	total: 8.3s	remaining: 25s
249:	learn: 0.1667758	total: 8.36s	remaining: 25.1s
250:	learn: 0.1665963	total: 8.43s	remaining: 25.2s
251:	learn: 0.1663052	total: 8.5s	remaining: 25.2s
252:	learn: 0.1661793	total: 8.56s	remaining: 25.3s
253:	learn: 0.1660793	total: 8.63s	remaining: 25.3s
254:	learn: 0.1659132	total: 8.68s	remaining: 25.4s
255:	learn: 0.1657595	total: 8.74s	remaining: 25.4s
256:	learn: 0.1655949	total: 8.8s	remaining: 25.4s
257:	learn: 0.1654485	total: 8.86s	remaining: 25.5s
258:	learn: 0.1652785	total: 8.91s	remaining: 25.5s
259:	learn: 0.1650025	total: 8.98s	remaining: 25.6s
260:	learn: 0.1648627	total: 9.05s	remaining: 25.6s
261:	learn: 0.1646790	total: 9.13s	remaining: 25.7s
262:	learn: 0.1644847	total: 9.21s	remaining: 25.8s
263:	learn: 0.1643860	total: 9.27s	remaining: 25.9s
264:	learn: 0.1642224	total: 9.35s	remaining: 25.9s
265:	learn: 0.1639939	total: 9.43s	remaining: 26s
266:	learn: 0.1638505	total: 9.5s	remaining: 26.1s
267:	learn: 0.1637579	total: 9.57s	remaining: 26.1s
268:	learn: 0.1635477	total: 9.62s	remaining: 26.1s
269:	learn: 0.1634202	total: 9.7s	remaining: 26.2s
270:	learn: 0.1633106	total: 9.77s	remaining: 26.3s
271:	learn: 0.1631100	total: 9.83s	remaining: 26.3s
272:	learn: 0.1629115	total: 9.89s	remaining: 26.3s
273:	learn: 0.1627779	total: 9.92s	remaining: 26.3s
274:	learn: 0.1626042	total: 9.98s	remaining: 26.3s
275:	learn: 0.1625174	total: 10s	remaining: 26.3s
276:	learn: 0.1622268	total: 10.1s	remaining: 26.4s
277:	learn: 0.1620791	total: 10.2s	remaining: 26.4s
278:	learn: 0.1619863	total: 10.2s	remaining: 26.4s
279:	learn: 0.1618083	total: 10.2s	remaining: 26.3s
280:	learn: 0.1616729	total: 10.3s	remaining: 26.3s
281:	learn: 0.1614595	total: 10.4s	remaining: 26.4s
282:	learn: 0.1612909	total: 10.4s	remaining: 26.4s
283:	learn: 0.1610430	total: 10.5s	remaining: 26.5s
284:	learn: 0.1608310	total: 10.6s	remaining: 26.5s
285:	learn: 0.1606581	total: 10.6s	remaining: 26.5s
286:	learn: 0.1604070	total: 10.7s	remaining: 26.5s
287:	learn: 0.1601877	total: 10.7s	remaining: 26.4s
288:	learn: 0.1601216	total: 10.7s	remaining: 26.4s
289:	learn: 0.1598905	total: 10.8s	remaining: 26.3s
290:	learn: 0.1597452	total: 10.8s	remaining: 26.3s
291:	learn: 0.1595825	total: 10.8s	remaining: 26.2s
292:	learn: 0.1593581	total: 10.8s	remaining: 26.2s
293:	learn: 0.1592109	total: 10.9s	remaining: 26.1s
294:	learn: 0.1590834	total: 10.9s	remaining: 26.1s
295:	learn: 0.1589003	total: 11s	remaining: 26s
296:	learn: 0.1586275	total: 11s	remaining: 26s
297:	learn: 0.1583971	total: 11s	remaining: 25.9s
298:	learn: 0.1581927	total: 11s	remaining: 25.9s
299:	learn: 0.1581032	total: 11.1s	remaining: 25.8s
300:	learn: 0.1580100	total: 11.1s	remaining: 25.8s
301:	learn: 0.1578703	total: 11.2s	remaining: 25.8s
302:	learn: 0.1577764	total: 11.2s	remaining: 25.8s
303:	learn: 0.1576677	total: 11.2s	remaining: 25.7s
304:	learn: 0.1575320	total: 11.3s	remaining: 25.7s
305:	learn: 0.1573743	total: 11.3s	remaining: 25.7s
306:	learn: 0.1573121	total: 11.4s	remaining: 25.7s
307:	learn: 0.1572339	total: 11.4s	remaining: 25.7s
308:	learn: 0.1571025	total: 11.5s	remaining: 25.6s
309:	learn: 0.1569855	total: 11.5s	remaining: 25.6s
310:	learn: 0.1567771	total: 11.5s	remaining: 25.5s
311:	learn: 0.1566422	total: 11.6s	remaining: 25.5s
312:	learn: 0.1564716	total: 11.6s	remaining: 25.5s
313:	learn: 0.1563800	total: 11.7s	remaining: 25.5s
314:	learn: 0.1561047	total: 11.7s	remaining: 25.4s
315:	learn: 0.1560256	total: 11.7s	remaining: 25.4s
316:	learn: 0.1559497	total: 11.8s	remaining: 25.3s
317:	learn: 0.1558561	total: 11.8s	remaining: 25.3s
318:	learn: 0.1557398	total: 11.8s	remaining: 25.3s
319:	learn: 0.1556154	total: 11.9s	remaining: 25.2s
320:	learn: 0.1554586	total: 11.9s	remaining: 25.2s
321:	learn: 0.1552313	total: 12s	remaining: 25.2s
322:	learn: 0.1551453	total: 12s	remaining: 25.2s
323:	learn: 0.1549253	total: 12.1s	remaining: 25.2s
324:	learn: 0.1548129	total: 12.1s	remaining: 25.2s
325:	learn: 0.1547217	total: 12.2s	remaining: 25.2s
326:	learn: 0.1545202	total: 12.2s	remaining: 25.2s
327:	learn: 0.1542823	total: 12.3s	remaining: 25.2s
328:	learn: 0.1540986	total: 12.4s	remaining: 25.2s
329:	learn: 0.1540106	total: 12.4s	remaining: 25.2s
330:	learn: 0.1538880	total: 12.5s	remaining: 25.2s
331:	learn: 0.1536408	total: 12.5s	remaining: 25.2s
332:	learn: 0.1535177	total: 12.5s	remaining: 25.1s
333:	learn: 0.1534068	total: 12.5s	remaining: 25s
334:	learn: 0.1532311	total: 12.6s	remaining: 24.9s
335:	learn: 0.1530423	total: 12.6s	remaining: 24.9s
336:	learn: 0.1529550	total: 12.6s	remaining: 24.8s
337:	learn: 0.1527616	total: 12.6s	remaining: 24.7s
338:	learn: 0.1525361	total: 12.6s	remaining: 24.6s
339:	learn: 0.1523904	total: 12.6s	remaining: 24.5s
340:	learn: 0.1522287	total: 12.7s	remaining: 24.5s
341:	learn: 0.1521009	total: 12.7s	remaining: 24.4s
342:	learn: 0.1519721	total: 12.7s	remaining: 24.3s
343:	learn: 0.1518262	total: 12.7s	remaining: 24.3s
344:	learn: 0.1517468	total: 12.7s	remaining: 24.2s
345:	learn: 0.1516351	total: 12.8s	remaining: 24.1s
346:	learn: 0.1514709	total: 12.8s	remaining: 24s
347:	learn: 0.1512714	total: 12.8s	remaining: 23.9s
348:	learn: 0.1510121	total: 12.8s	remaining: 23.9s
349:	learn: 0.1507853	total: 12.8s	remaining: 23.8s
350:	learn: 0.1505925	total: 12.8s	remaining: 23.7s
351:	learn: 0.1504152	total: 12.8s	remaining: 23.6s
352:	learn: 0.1501805	total: 12.9s	remaining: 23.6s
353:	learn: 0.1500228	total: 12.9s	remaining: 23.5s
354:	learn: 0.1499214	total: 12.9s	remaining: 23.4s
355:	learn: 0.1497562	total: 12.9s	remaining: 23.3s
356:	learn: 0.1496189	total: 12.9s	remaining: 23.3s
357:	learn: 0.1494981	total: 12.9s	remaining: 23.2s
358:	learn: 0.1493687	total: 12.9s	remaining: 23.1s
359:	learn: 0.1492479	total: 13s	remaining: 23s
360:	learn: 0.1490954	total: 13s	remaining: 23s
361:	learn: 0.1489396	total: 13s	remaining: 22.9s
362:	learn: 0.1488604	total: 13s	remaining: 22.8s
363:	learn: 0.1487557	total: 13s	remaining: 22.8s
364:	learn: 0.1485559	total: 13s	remaining: 22.7s
365:	learn: 0.1483283	total: 13.1s	remaining: 22.6s
366:	learn: 0.1482190	total: 13.1s	remaining: 22.5s
367:	learn: 0.1481478	total: 13.1s	remaining: 22.5s
368:	learn: 0.1480300	total: 13.1s	remaining: 22.4s
369:	learn: 0.1479625	total: 13.1s	remaining: 22.3s
370:	learn: 0.1479145	total: 13.1s	remaining: 22.3s
371:	learn: 0.1477239	total: 13.1s	remaining: 22.2s
372:	learn: 0.1475842	total: 13.2s	remaining: 22.1s
373:	learn: 0.1474566	total: 13.2s	remaining: 22.1s
374:	learn: 0.1474146	total: 13.2s	remaining: 22s
375:	learn: 0.1472238	total: 13.2s	remaining: 21.9s
376:	learn: 0.1470375	total: 13.2s	remaining: 21.9s
377:	learn: 0.1468888	total: 13.2s	remaining: 21.8s
378:	learn: 0.1467717	total: 13.3s	remaining: 21.7s
379:	learn: 0.1466506	total: 13.3s	remaining: 21.7s
380:	learn: 0.1465355	total: 13.3s	remaining: 21.6s
381:	learn: 0.1463820	total: 13.3s	remaining: 21.5s
382:	learn: 0.1461247	total: 13.3s	remaining: 21.4s
383:	learn: 0.1459878	total: 13.3s	remaining: 21.4s
384:	learn: 0.1458094	total: 13.3s	remaining: 21.3s
385:	learn: 0.1457396	total: 13.4s	remaining: 21.3s
386:	learn: 0.1455845	total: 13.4s	remaining: 21.2s
387:	learn: 0.1453747	total: 13.4s	remaining: 21.1s

CatBoostClassifier()

In [83]:
test = pd.read_csv("/content/test_data.csv")
test['Timestamp'] = pd.to_datetime(test['Timestamp'])

In [84]:
predictions = model.predict(test.drop(columns = ['ID']))
print(len(predictions), len(test['ID']))

7500 7500

In [85]:
submission2 = pd.DataFrame({
    'subtaskID':2,
    'datapointID': test['ID'],
    'answer':predictions.flatten(),
})

In [86]:

submission = pd.concat([submission1, submission2], ignore_index = True)
submission.to_csv('submission.csv', index = False)

In [87]:
submission

       subtaskID  datapointID answer
0              1        12633     PM
1              1        24448     PM
2              1        14208     AM
3              1        39654     AM
4              1          337     AM
...          ...          ...    ...
14995          2        38228      0
14996          2         8568      2
14997          2         1435      1
14998          2         9879      0
14999          2        17025      2

[15000 rows x 3 columns]

In [88]:
submission.to_csv('final.csv', index = False)